In [18]:
import pandas as pd
from pathlib import Path

pd.options.mode.copy_on_write = True
pd.options.future.infer_string = True
pd.options.plotting.backend = "plotly"

In [19]:
this_file_dir = Path('.').resolve()
bld = this_file_dir / "bld"

In [21]:
clean_chs = pd.read_feather(bld / "clean_chs_data.arrow")
clean_nlsy = pd.read_feather(bld / "clean_nlsy_data.arrow")

In [22]:
clean_chs

              momid  age      bpiA      bpiB      bpiC      bpiD      bpiE
childid year
201     1993      2    0      <NA>      <NA>      <NA>      <NA>      <NA>
        1994      2    1      <NA>      <NA>      <NA>      <NA>      <NA>
        1996      2    3      <NA>      <NA>      <NA>      <NA>      <NA>
        1998      2    5  0.954977  0.252469  0.761378 -0.103273  0.547242
        2000      2    7      <NA> -0.305677  1.376603 -0.060863 -0.735066
...             ...  ...       ...       ...       ...       ...       ...
1255601 1983  12556    5      <NA>      <NA>      <NA>      <NA>      <NA>
        1985  12556    7  -0.42874 -1.727758 -1.045441 -0.696726 -0.735066
        1987  12556    9  0.249955 -2.236943 -1.621489   0.52778   0.59118
        1989  12556   11      <NA>      <NA>      <NA>      <NA>      <NA>
        1991  12556   13      <NA>      <NA>      <NA>      <NA>      <NA>

[17656 rows x 7 columns]

In [23]:
clean_nlsy

,,momid,birth_order,anxiety_mood,anxiety_complain,headstrong_tense,antisocial_cheat,anxiety_fearful,headstrong_argues,hyperactive_concentration,hyperactive_confused,...,antisocial,anxiety,headstrong,hyperactive,dependence,peer,additional_gethim,additional_hangout,additional_secretive,additional_worries
childid,year,,,,,,,,,,,,,,,,,,,,,
201,1986,2,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
202,1986,2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
301,1986,3,1,not true,not true,not true,not true,sometimes true,not true,not true,not true,...,0.0,0.2,0.0,0.2,NaN,0.333333,NaN,NaN,NaN,NaN
302,1986,3,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
303,1986,3,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1267201,2010,12672,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1267202,2010,12672,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1267301,2010,12673,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1267302,2010,12673,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1267501,2010,12675,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
def merge_chs_and_nlsy(clean_chs, clean_nlsy):
    
    merged_data = pd.merge(clean_chs, clean_nlsy, how='left', on=['childid', 'year'])
    merged_data_age_filtered = merged_data[(merged_data['age'] >= 5) & (merged_data['age'] <= 13)]

    return merged_data_age_filtered

merged_data = merge_chs_and_nlsy(clean_chs, clean_nlsy)

In [25]:
merged_data

              momid_x  age      bpiA      bpiB      bpiC      bpiD      bpiE  \
childid year
201     1998        2    5  0.954977  0.252469  0.761378 -0.103273  0.547242
        2000        2    7      <NA> -0.305677  1.376603 -0.060863 -0.735066
        2002        2    9  -0.39311  1.137765   1.37505  1.145124   0.59118
        2004        2   11  0.890382  1.162996  1.386174  1.097578  0.597735
        2006        2   13      <NA>      <NA>      <NA>      <NA>      <NA>
...               ...  ...       ...       ...       ...       ...       ...
1255601 1983    12556    5      <NA>      <NA>      <NA>      <NA>      <NA>
        1985    12556    7  -0.42874 -1.727758 -1.045441 -0.696726 -0.735066
        1987    12556    9  0.249955 -2.236943 -1.621489   0.52778   0.59118
        1989    12556   11      <NA>      <NA>      <NA>      <NA>      <NA>
        1991    12556   13      <NA>      <NA>      <NA>      <NA>      <NA>

              momid_y  birth_order anxiety_mood  ... antisocial anxiety  \
childid year                                     ...
201     1998        2          1.0     not true  ...   0.000000     0.2
        2000        2          1.0     not true  ...   0.000000     0.4
        2002        2          1.0     not true  ...   0.333333     0.0
        2004        2          1.0     not true  ...   0.000000     0.0
        2006        2          1.0     not true  ...   0.000000     0.2
...               ...          ...          ...  ...        ...     ...
1255601 1983     <NA>          NaN          NaN  ...        NaN     NaN
        1985     <NA>          NaN          NaN  ...        NaN     NaN
        1987     <NA>          NaN          NaN  ...        NaN     NaN
        1989     <NA>          NaN          NaN  ...        NaN     NaN
        1991     <NA>          NaN          NaN  ...        NaN     NaN

             headstrong hyperactive dependence      peer additional_gethim  \
childid year
201     1998        0.2         0.4        NaN  0.000000          not true
        2000        0.0         0.4        NaN  0.333333          not true
        2002        0.0         0.0        NaN  0.000000          not true
        2004        0.0         0.0        NaN  0.000000          not true
        2006        0.2         0.0        NaN  0.000000          not true
...                 ...         ...        ...       ...               ...
1255601 1983        NaN         NaN        NaN       NaN               NaN
        1985        NaN         NaN        NaN       NaN               NaN
        1987        NaN         NaN        NaN       NaN               NaN
        1989        NaN         NaN        NaN       NaN               NaN
        1991        NaN         NaN        NaN       NaN               NaN

             additional_hangout additional_secretive additional_worries
childid year
201     1998           not true             not true     sometimes true
        2000           not true             not true           not true
        2002           not true             not true           not true
        2004           not true             not true           not true
        2006           not true             not true     sometimes true
...                         ...                  ...                ...
1255601 1983                NaN                  NaN                NaN
        1985                NaN                  NaN                NaN
        1987                NaN                  NaN                NaN
        1989                NaN                  NaN                NaN
        1991                NaN                  NaN                NaN

[11035 rows x 47 columns]

In [26]:
clean_merged = pd.merge(clean_chs,clean_nlsy,left_index=True, right_index=True, how='left', suffixes= (None, 'drop'))


clean_merged = clean_merged.drop(columns='momiddrop')
clean_merged

              momid  age      bpiA      bpiB      bpiC      bpiD      bpiE  \
childid year
201     1993      2    0      <NA>      <NA>      <NA>      <NA>      <NA>
        1994      2    1      <NA>      <NA>      <NA>      <NA>      <NA>
        1996      2    3      <NA>      <NA>      <NA>      <NA>      <NA>
        1998      2    5  0.954977  0.252469  0.761378 -0.103273  0.547242
        2000      2    7      <NA> -0.305677  1.376603 -0.060863 -0.735066
...             ...  ...       ...       ...       ...       ...       ...
1255601 1983  12556    5      <NA>      <NA>      <NA>      <NA>      <NA>
        1985  12556    7  -0.42874 -1.727758 -1.045441 -0.696726 -0.735066
        1987  12556    9  0.249955 -2.236943 -1.621489   0.52778   0.59118
        1989  12556   11      <NA>      <NA>      <NA>      <NA>      <NA>
        1991  12556   13      <NA>      <NA>      <NA>      <NA>      <NA>

              birth_order anxiety_mood anxiety_complain  ... antisocial  \
childid year                                             ...
201     1993          NaN          NaN              NaN  ...        NaN
        1994          1.0          NaN              NaN  ...        NaN
        1996          1.0          NaN              NaN  ...        NaN
        1998          1.0     not true         not true  ...        0.0
        2000          1.0     not true   sometimes true  ...        0.0
...                   ...          ...              ...  ...        ...
1255601 1983          NaN          NaN              NaN  ...        NaN
        1985          NaN          NaN              NaN  ...        NaN
        1987          NaN          NaN              NaN  ...        NaN
        1989          NaN          NaN              NaN  ...        NaN
        1991          NaN          NaN              NaN  ...        NaN

             anxiety headstrong hyperactive dependence      peer  \
childid year
201     1993     NaN        NaN         NaN        NaN       NaN
        1994     NaN        NaN         NaN        NaN       NaN
        1996     NaN        NaN         NaN        NaN       NaN
        1998     0.2        0.2         0.4        NaN  0.000000
        2000     0.4        0.0         0.4        NaN  0.333333
...              ...        ...         ...        ...       ...
1255601 1983     NaN        NaN         NaN        NaN       NaN
        1985     NaN        NaN         NaN        NaN       NaN
        1987     NaN        NaN         NaN        NaN       NaN
        1989     NaN        NaN         NaN        NaN       NaN
        1991     NaN        NaN         NaN        NaN       NaN

             additional_gethim additional_hangout additional_secretive  \
childid year
201     1993               NaN                NaN                  NaN
        1994               NaN                NaN                  NaN
        1996               NaN                NaN                  NaN
        1998          not true           not true             not true
        2000          not true           not true             not true
...                        ...                ...                  ...
1255601 1983               NaN                NaN                  NaN
        1985               NaN                NaN                  NaN
        1987               NaN                NaN                  NaN
        1989               NaN                NaN                  NaN
        1991               NaN                NaN                  NaN

             additional_worries
childid year
201     1993                NaN
        1994                NaN
        1996                NaN
        1998     sometimes true
        2000           not true
...                         ...
1255601 1983                NaN
        1985                NaN
        1987                NaN
        1989                NaN
        1991                NaN

[17656 rows x 46 columns]

In [27]:
clean_merged[(clean_merged['age']<=13) & (clean_merged['age']>=5)]

              momid  age      bpiA      bpiB      bpiC      bpiD      bpiE  \
childid year
201     1998      2    5  0.954977  0.252469  0.761378 -0.103273  0.547242
        2000      2    7      <NA> -0.305677  1.376603 -0.060863 -0.735066
        2002      2    9  -0.39311  1.137765   1.37505  1.145124   0.59118
        2004      2   11  0.890382  1.162996  1.386174  1.097578  0.597735
        2006      2   13      <NA>      <NA>      <NA>      <NA>      <NA>
...             ...  ...       ...       ...       ...       ...       ...
1255601 1983  12556    5      <NA>      <NA>      <NA>      <NA>      <NA>
        1985  12556    7  -0.42874 -1.727758 -1.045441 -0.696726 -0.735066
        1987  12556    9  0.249955 -2.236943 -1.621489   0.52778   0.59118
        1989  12556   11      <NA>      <NA>      <NA>      <NA>      <NA>
        1991  12556   13      <NA>      <NA>      <NA>      <NA>      <NA>

              birth_order anxiety_mood anxiety_complain  ... antisocial  \
childid year                                             ...
201     1998          1.0     not true         not true  ...   0.000000
        2000          1.0     not true   sometimes true  ...   0.000000
        2002          1.0     not true         not true  ...   0.333333
        2004          1.0     not true         not true  ...   0.000000
        2006          1.0     not true         not true  ...   0.000000
...                   ...          ...              ...  ...        ...
1255601 1983          NaN          NaN              NaN  ...        NaN
        1985          NaN          NaN              NaN  ...        NaN
        1987          NaN          NaN              NaN  ...        NaN
        1989          NaN          NaN              NaN  ...        NaN
        1991          NaN          NaN              NaN  ...        NaN

             anxiety headstrong hyperactive dependence      peer  \
childid year
201     1998     0.2        0.2         0.4        NaN  0.000000
        2000     0.4        0.0         0.4        NaN  0.333333
        2002     0.0        0.0         0.0        NaN  0.000000
        2004     0.0        0.0         0.0        NaN  0.000000
        2006     0.2        0.2         0.0        NaN  0.000000
...              ...        ...         ...        ...       ...
1255601 1983     NaN        NaN         NaN        NaN       NaN
        1985     NaN        NaN         NaN        NaN       NaN
        1987     NaN        NaN         NaN        NaN       NaN
        1989     NaN        NaN         NaN        NaN       NaN
        1991     NaN        NaN         NaN        NaN       NaN

             additional_gethim additional_hangout additional_secretive  \
childid year
201     1998          not true           not true             not true
        2000          not true           not true             not true
        2002          not true           not true             not true
        2004          not true           not true             not true
        2006          not true           not true             not true
...                        ...                ...                  ...
1255601 1983               NaN                NaN                  NaN
        1985               NaN                NaN                  NaN
        1987               NaN                NaN                  NaN
        1989               NaN                NaN                  NaN
        1991               NaN                NaN                  NaN

             additional_worries
childid year
201     1998     sometimes true
        2000           not true
        2002           not true
        2004           not true
        2006     sometimes true
...                         ...
1255601 1983                NaN
        1985                NaN
        1987                NaN
        1989                NaN
        1991                NaN

[11035 rows x 46 columns]

In [27]:
merged_data

              momid_x  age      bpiA      bpiB      bpiC      bpiD      bpiE  \
childid year
201     1998        2    5  0.954977  0.252469  0.761378 -0.103273  0.547242
        2000        2    7      <NA> -0.305677  1.376603 -0.060863 -0.735066
        2002        2    9  -0.39311  1.137765   1.37505  1.145124   0.59118
        2004        2   11  0.890382  1.162996  1.386174  1.097578  0.597735
        2006        2   13      <NA>      <NA>      <NA>      <NA>      <NA>
...               ...  ...       ...       ...       ...       ...       ...
1255601 1983    12556    5      <NA>      <NA>      <NA>      <NA>      <NA>
        1985    12556    7  -0.42874 -1.727758 -1.045441 -0.696726 -0.735066
        1987    12556    9  0.249955 -2.236943 -1.621489   0.52778   0.59118
        1989    12556   11      <NA>      <NA>      <NA>      <NA>      <NA>
        1991    12556   13      <NA>      <NA>      <NA>      <NA>      <NA>

              momid_y  birth_order anxiety_mood  ... antisocial anxiety  \
childid year                                     ...
201     1998        2          1.0     not true  ...   0.000000     0.2
        2000        2          1.0     not true  ...   0.000000     0.4
        2002        2          1.0     not true  ...   0.333333     0.0
        2004        2          1.0     not true  ...   0.000000     0.0
        2006        2          1.0     not true  ...   0.000000     0.2
...               ...          ...          ...  ...        ...     ...
1255601 1983     <NA>          NaN          NaN  ...        NaN     NaN
        1985     <NA>          NaN          NaN  ...        NaN     NaN
        1987     <NA>          NaN          NaN  ...        NaN     NaN
        1989     <NA>          NaN          NaN  ...        NaN     NaN
        1991     <NA>          NaN          NaN  ...        NaN     NaN

             headstrong hyperactive dependence      peer additional_gethim  \
childid year
201     1998        0.2         0.4        NaN  0.000000          not true
        2000        0.0         0.4        NaN  0.333333          not true
        2002        0.0         0.0        NaN  0.000000          not true
        2004        0.0         0.0        NaN  0.000000          not true
        2006        0.2         0.0        NaN  0.000000          not true
...                 ...         ...        ...       ...               ...
1255601 1983        NaN         NaN        NaN       NaN               NaN
        1985        NaN         NaN        NaN       NaN               NaN
        1987        NaN         NaN        NaN       NaN               NaN
        1989        NaN         NaN        NaN       NaN               NaN
        1991        NaN         NaN        NaN       NaN               NaN

             additional_hangout additional_secretive additional_worries
childid year
201     1998           not true             not true     sometimes true
        2000           not true             not true           not true
        2002           not true             not true           not true
        2004           not true             not true           not true
        2006           not true             not true     sometimes true
...                         ...                  ...                ...
1255601 1983                NaN                  NaN                NaN
        1985                NaN                  NaN                NaN
        1987                NaN                  NaN                NaN
        1989                NaN                  NaN                NaN
        1991                NaN                  NaN                NaN

[11035 rows x 47 columns]